apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello  hello world"
          errorlog=error.log
          echo "until loop - trigger run - 5"
          i=10
          until [ $i == 1 ]
          do
              echo "countdown: $i secs" >> $errorlog 2>&1;
              i=$((i-1))
              sleep 1
          done
          echo "i value is $i"
          
          if grep -q "countdown" $errorlog; then
              exit 1
          fi
